package edu.duke.cabig.c3pr.grid.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.apache.axis.utils.ClassUtils;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import edu.duke.cabig.c3pr.grid.stubs.C3PRStudyConsumerPortType;
import edu.duke.cabig.c3pr.grid.stubs.service.C3PRStudyConsumerServiceAddressingLocator;
import edu.duke.cabig.c3pr.grid.common.C3PRStudyConsumerI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class C3PRStudyConsumerClient extends ServiceSecurityClient implements C3PRStudyConsumerI {	
	protected C3PRStudyConsumerPortType portType;
	private Object portTypeMutex;

	public C3PRStudyConsumerClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public C3PRStudyConsumerClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	   	initialize();
	}
	
	public C3PRStudyConsumerClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public C3PRStudyConsumerClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
		initialize();
	}
	
	private void initialize() throws RemoteException {
	    this.portTypeMutex = new Object();
		this.portType = createPortType();
	}

	private C3PRStudyConsumerPortType createPortType() throws RemoteException {

		C3PRStudyConsumerServiceAddressingLocator locator = new C3PRStudyConsumerServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		C3PRStudyConsumerPortType port = null;
		try {
			port = locator.getC3PRStudyConsumerPortTypePort(getEndpointReference());
		} catch (Exception e) {
			throw new RemoteException("Unable to locate portType:" + e.getMessage(), e);
		}

		return port;
	}
	
	public GetResourcePropertyResponse getResourceProperty(QName resourcePropertyQName) throws RemoteException {
		return portType.getResourceProperty(resourcePropertyQName);
	}

	public static void usage(){
		System.out.println(C3PRStudyConsumerClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  C3PRStudyConsumerClient client = new C3PRStudyConsumerClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
	public edu.duke.cabig.c3pr.domain.Study createOrUpdate(edu.duke.cabig.c3pr.domain.Study study) throws RemoteException, edu.duke.cabig.c3pr.grid.stubs.types.StudyValidationException, edu.duke.cabig.c3pr.grid.stubs.types.StudyCreateOrUpdateException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"createOrUpdate");
        edu.duke.cabig.c3pr.grid.stubs.CreateOrUpdateRequest params = new edu.duke.cabig.c3pr.grid.stubs.CreateOrUpdateRequest();
        edu.duke.cabig.c3pr.grid.stubs.CreateOrUpdateRequestStudy studyContainer = new edu.duke.cabig.c3pr.grid.stubs.CreateOrUpdateRequestStudy();
        studyContainer.setStudy(study);
        params.setStudy(studyContainer);
        edu.duke.cabig.c3pr.grid.stubs.CreateOrUpdateResponse boxedResult = portType.createOrUpdate(params);
        return boxedResult.getStudy();
      }
    }

}
