
package edu.duke.cabig.c3pr.webservice.subjectregistration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubjectRegistrationService", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", wsdlLocation = "file:/Users/kruttikagarwal/Documents/workspace/c3pr/documentation/design/essn/SubjectRegistration/SubjectRegistration.wsdl")
public class SubjectRegistrationService
    extends Service
{

    private final static URL SUBJECTREGISTRATIONSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kruttikagarwal/Documents/workspace/c3pr/documentation/design/essn/SubjectRegistration/SubjectRegistration.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SUBJECTREGISTRATIONSERVICE_WSDL_LOCATION = url;
    }

    public SubjectRegistrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubjectRegistrationService() {
        super(SUBJECTREGISTRATIONSERVICE_WSDL_LOCATION, new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", "SubjectRegistrationService"));
    }

    /**
     * 
     * @return
     *     returns SubjectRegistration
     */
    @WebEndpoint(name = "SubjectRegistration")
    public SubjectRegistration getSubjectRegistration() {
        return (SubjectRegistration)super.getPort(new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", "SubjectRegistration"), SubjectRegistration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubjectRegistration
     */
    @WebEndpoint(name = "SubjectRegistration")
    public SubjectRegistration getSubjectRegistration(WebServiceFeature... features) {
        return (SubjectRegistration)super.getPort(new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", "SubjectRegistration"), SubjectRegistration.class, features);
    }

}
