
package edu.duke.cabig.c3pr.webservice.subjectregistration;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SubjectRegistrationRejectedExceptionFault", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService")
public class SubjectRegistrationRejectedExceptionFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SubjectRegistrationRejectedExceptionFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SubjectRegistrationRejectedExceptionFaultMessage(String message, SubjectRegistrationRejectedExceptionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public SubjectRegistrationRejectedExceptionFaultMessage(String message, SubjectRegistrationRejectedExceptionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: edu.duke.cabig.c3pr.webservice.subjectregistration.SubjectRegistrationRejectedExceptionFault
     */
    public SubjectRegistrationRejectedExceptionFault getFaultInfo() {
        return faultInfo;
    }

}
