
package edu.duke.cabig.c3pr.webservice.subjectregistration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SubjectRegistration", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    edu.duke.cabig.c3pr.webservice.subjectregistration.ObjectFactory.class,
    edu.duke.cabig.c3pr.webservice.iso21090.ObjectFactory.class
})
public interface SubjectRegistration {


    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.InitiateSubjectEnrollmentResponse
     * @throws InvalidStudyProtocolExceptionFaultMessage
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws SubjectRegistrationRejectedExceptionFaultMessage
     * @throws InvalidSiteExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     * @throws SubjectAlreadyRegisteredExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "InitiateSubjectEnrollmentResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public InitiateSubjectEnrollmentResponse initiateSubjectEnrollment(
        @WebParam(name = "InitiateSubjectEnrollmentRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        InitiateSubjectEnrollmentRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidSiteExceptionFaultMessage, InvalidStudyProtocolExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, SubjectAlreadyRegisteredExceptionFaultMessage, SubjectRegistrationRejectedExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.ChangeStudySubjectEpochAssignmentResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InvalidStudyProtocolExceptionFaultMessage
     * @throws SubjectRegistrationRejectedExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "ChangeStudySubjectEpochAssignmentResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public ChangeStudySubjectEpochAssignmentResponse changeStudySubjectEpochAssignment(
        @WebParam(name = "ChangeStudySubjectEpochAssignmentRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        ChangeStudySubjectEpochAssignmentRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudyProtocolExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage, SubjectRegistrationRejectedExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.ReconsentStudySubjectResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InvalidStudyProtocolExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "ReconsentStudySubjectResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public ReconsentStudySubjectResponse reconsentSubject(
        @WebParam(name = "ReconsentStudySubjectRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        ReconsentStudySubjectRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudyProtocolExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.TakeSubjectOffStudyResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "TakeSubjectOffStudyResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public TakeSubjectOffStudyResponse takeSubjectOffStudy(
        @WebParam(name = "TakeSubjectOffStudyRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        TakeSubjectOffStudyRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.FailSubjectScreeningResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "FailSubjectScreeningResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public FailSubjectScreeningResponse failSubjectScreening(
        @WebParam(name = "FailSubjectScreeningRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        FailSubjectScreeningRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.DiscontinueEnrollmentResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "DiscontinueEnrollmentResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public DiscontinueEnrollmentResponse discontinueSubjectEnrollment(
        @WebParam(name = "DiscontinueEnrollmentRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        DiscontinueEnrollmentRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.RetrieveAccrualDataResponse
     * @throws InvalidStudyProtocolExceptionFaultMessage
     * @throws InvalidSiteExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "RetrieveAccrualDataResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public RetrieveAccrualDataResponse retrieveAccuralData(
        @WebParam(name = "RetrieveAccrualDataRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        RetrieveAccrualDataRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidSiteExceptionFaultMessage, InvalidStudyProtocolExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.GenerateSummary3ReportResponse
     * @throws InvalidSiteExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "GenerateSummary3ReportResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public GenerateSummary3ReportResponse generateSummary3Report(
        @WebParam(name = "GenerateSummary3ReportRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        GenerateSummary3ReportRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidSiteExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.UpdateRegistrationResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "UpdateRegistrationResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public UpdateRegistrationResponse updateSubjectRegistration(
        @WebParam(name = "UpdateRegistrationRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        UpdateRegistrationRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.ImportRegistrationsResponse
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "ImportRegistrationsResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public ImportRegistrationsResponse importRegistrations(
        @WebParam(name = "ImportRegistrationsRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        ImportRegistrationsRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.QuerySubjectRegistrationResponse
     * @throws InvalidQueryExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "QuerySubjectRegistrationResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public QuerySubjectRegistrationResponse querySubjectRegistration(
        @WebParam(name = "QuerySubjectRegistrationRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        QuerySubjectRegistrationRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidQueryExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistration.RetrieveSubjectDemographyHistoryResponse
     * @throws NoSuchPatientExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "RetrieveSubjectDemographyHistoryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
    public RetrieveSubjectDemographyHistoryResponse retrieveSubjectDemographyHistory(
        @WebParam(name = "RetrieveSubjectDemographyHistoryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistrationService", partName = "parameters")
        RetrieveSubjectDemographyHistoryRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, NoSuchPatientExceptionFaultMessage
    ;

}
