DROP SEQUENCE IDENTIFIERS_ID_SEQ;
DROP TABLE IDENTIFIERS CASCADE CONSTRAINTS ;

DROP SEQUENCE ADDRESSES_ID_SEQ;
DROP TABLE ADDRESSES CASCADE CONSTRAINTS ;

DROP SEQUENCE PARTICIPANTS_ID_SEQ;
DROP TABLE PARTICIPANTS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDIES_ID_SEQ;
DROP TABLE STUDIES CASCADE CONSTRAINTS ;

DROP SEQUENCE EPOCHS_ID_SEQ;
DROP TABLE EPOCHS CASCADE CONSTRAINTS ;

DROP SEQUENCE ARMS_ID_SEQ;
DROP TABLE ARMS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDY_SITES_ID_SEQ;
DROP TABLE STUDY_SITES CASCADE CONSTRAINTS ;

DROP SEQUENCE HEALTHCARE_SITES_ID_SEQ;
DROP TABLE HEALTHCARE_SITES CASCADE CONSTRAINTS;

DROP SEQUENCE INVESTIGATORS_ID_SEQ;
DROP TABLE INVESTIGATORS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDY_INVESTIGATORS_ID_SEQ;
DROP TABLE STUDY_INVESTIGATORS CASCADE CONSTRAINTS ;

DROP SEQUENCE HC_SITE_INVESTIGATORS_ID_SEQ;
DROP TABLE HC_SITE_INVESTIGATORS CASCADE CONSTRAINTS ;

DROP SEQUENCE SCHEDULED_ARMS_ID_SEQ;
DROP TABLE SCHEDULED_ARMS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDY_PARTICIPANT_ASSIG_ID_SEQ;
DROP TABLE STUDY_PARTICIPANT_ASSIGNMENTS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDY_PERSONNELS_ID_SEQ;
DROP TABLE STUDY_PERSONNELS CASCADE CONSTRAINTS ;

DROP SEQUENCE RESEARCH_STAFFS_ID_SEQ;
DROP TABLE RESEARCH_STAFFS CASCADE CONSTRAINTS ;

DROP SEQUENCE ELIGIBILITY_CRITERIAS_ID_SEQ;
DROP TABLE ELIGIBILITY_CRITERIAS CASCADE CONSTRAINTS ;

DROP SEQUENCE PRT_ELIGIBILITY_ANS_ID_SEQ;
DROP TABLE SUBJECT_ELIGIBILITY_ANSWERS CASCADE CONSTRAINTS ;

DROP SEQUENCE STUDY_DISEASES_ID_SEQ;
DROP TABLE STUDY_DISEASES CASCADE CONSTRAINTS ;

DROP SEQUENCE DISEASE_TERMS_ID_SEQ;
DROP TABLE DISEASE_TERMS CASCADE CONSTRAINTS ;

DROP SEQUENCE DISEASE_CATEGORIES_ID_SEQ;
DROP TABLE DISEASE_CATEGORIES CASCADE CONSTRAINTS ;

DROP SEQUENCE STRATIFICATION_CRI_ID_SEQ;
DROP TABLE STRATIFICATION_CRITERION CASCADE CONSTRAINTS;

DROP SEQUENCE STRATIFICATION_CRI_ANS_ID_SEQ;
DROP TABLE STRATIFICATION_CRI_PER_ANS CASCADE CONSTRAINTS;

DROP SEQUENCE PRT_STRAT_ANS_ID_SEQ;
DROP TABLE SUBJECT_STRATIFICATION_ANSWERS CASCADE CONSTRAINTS;

DROP SEQUENCE DISEASE_HISTORY_ID_SEQ;
DROP TABLE DISEASE_HISTORY CASCADE CONSTRAINTS;

DROP SEQUENCE ANATOMIC_SITES_ID_SEQ;
DROP TABLE ANATOMIC_SITES CASCADE CONSTRAINTS;

DROP SEQUENCE CONTACT_MECHANISMS_ID_SEQ;
DROP TABLE CONTACT_MECHANISMS CASCADE CONSTRAINTS;

DROP SEQUENCE ORGANIZATIONS_ID_SEQ;
DROP TABLE ORGANIZATIONS CASCADE CONSTRAINTS;
