  DELETE FROM CONTACT_MECHANISMS;
  DELETE FROM RESEARCH_STAFF;
  DELETE FROM HC_SITE_INVESTIGATORS;
  DELETE FROM INVESTIGATORS;
  DELETE FROM IDENTIFIERS;
  DELETE FROM ORGANIZATIONS CASCADE WHERE ID BETWEEN 10000 AND 10005;
  DELETE FROM ADDRESSES CASCADE WHERE ID BETWEEN 10000 AND 10005;