package edu.duke.cabig.c3pr.domain;

import java.util.Date;


/**
 * Letter generated by MyEclipse - Hibernate Tools
 */

public class Letter implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String typeCode;
     private Integer participantId;
     private Integer relationshipId;
     private Date letterGenerationDate;
     private String content;
     private String outputFormat;
     private String outputFormatVersion;


    // Constructors

    /** default constructor */
    public Letter() {
    }

	/** minimal constructor */
    public Letter(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Letter(Integer id, String typeCode, Integer participantId, Integer relationshipId, Date letterGenerationDate, String content, String outputFormat, String outputFormatVersion) {
        this.id = id;
        this.typeCode = typeCode;
        this.participantId = participantId;
        this.relationshipId = relationshipId;
        this.letterGenerationDate = letterGenerationDate;
        this.content = content;
        this.outputFormat = outputFormat;
        this.outputFormatVersion = outputFormatVersion;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public Integer getParticipantId() {
        return this.participantId;
    }
    
    public void setParticipantId(Integer participantId) {
        this.participantId = participantId;
    }

    public Integer getRelationshipId() {
        return this.relationshipId;
    }
    
    public void setRelationshipId(Integer relationshipId) {
        this.relationshipId = relationshipId;
    }

    public Date getLetterGenerationDate() {
        return this.letterGenerationDate;
    }
    
    public void setLetterGenerationDate(Date letterGenerationDate) {
        this.letterGenerationDate = letterGenerationDate;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getOutputFormat() {
        return this.outputFormat;
    }
    
    public void setOutputFormat(String outputFormat) {
        this.outputFormat = outputFormat;
    }

    public String getOutputFormatVersion() {
        return this.outputFormatVersion;
    }
    
    public void setOutputFormatVersion(String outputFormatVersion) {
        this.outputFormatVersion = outputFormatVersion;
    }
   








}