INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10001','1','512 South Magnum Street Suite 400','Durham','NC','USA','27710');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10002','1','10 Center Drive Bldg 10','Bethesda','MD','USA','20892');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10003','1','6130 Executive Blvd','Rockville','MD','USA','20852');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10004','1','12359 Sunrise Valley Drive','Reston','VA','USA','20191');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10005','1','Medical Center Boulevard','Winston-Salem','NC','USA','27157');

INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10001', '1','DUKE GRID ID', 'Duke University Comprehensive Cancer Center', '10001');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10002', '1', 'NCI GRID ID','Warren Grant Magnuson Clinical Center', '10002');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10003', '1', 'NCI GRID ID','National Cancer Institute', '10003');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10004', '1','C3PR GRID ID', 'C3PR', '10004');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10005', '1','WF GRID ID', 'Wake Forest Comprehensive Cancer Center', '10005');