
package edu.duke.cabig.c3pr.webservice.testclient.studyutility;

import javax.xml.ws.WebFault;
import edu.duke.cabig.c3pr.webservice.testclient.common.SecurityExceptionFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SecurityExceptionFault", targetNamespace = "http://enterpriseservices.nci.nih.gov/Common")
public class SecurityExceptionFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecurityExceptionFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SecurityExceptionFaultMessage(String message, SecurityExceptionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SecurityExceptionFaultMessage(String message, SecurityExceptionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: edu.duke.cabig.c3pr.webservice.testclient.common.SecurityExceptionFault
     */
    public SecurityExceptionFault getFaultInfo() {
        return faultInfo;
    }

}
