
package edu.duke.cabig.c3pr.webservice.testclient.studyutility;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "StudyUtilityFault", targetNamespace = "http://enterpriseservices.nci.nih.gov/StudyUtilityService")
public class StudyUtilityFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StudyUtilityFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public StudyUtilityFaultMessage(String message, StudyUtilityFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public StudyUtilityFaultMessage(String message, StudyUtilityFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: edu.duke.cabig.c3pr.webservice.testclient.studyutility.StudyUtilityFault
     */
    public StudyUtilityFault getFaultInfo() {
        return faultInfo;
    }

}
