
package edu.duke.cabig.c3pr.webservice.subjectmanagement;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "InvalidSubjectDataExceptionFault", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectManagementService")
public class InvalidSubjectDataExceptionFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidSubjectDataExceptionFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidSubjectDataExceptionFaultMessage(String message, InvalidSubjectDataExceptionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidSubjectDataExceptionFaultMessage(String message, InvalidSubjectDataExceptionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: edu.duke.cabig.c3pr.webservice.subjectmanagement.InvalidSubjectDataExceptionFault
     */
    public InvalidSubjectDataExceptionFault getFaultInfo() {
        return faultInfo;
    }

}
