  DELETE FROM CONTACT_MECHANISMS CASCADE;
  DELETE FROM RESEARCH_STAFF CASCADE;
  DELETE FROM HC_SITE_INVESTIGATORS CASCADE;
  DELETE FROM INVESTIGATORS CASCADE;
  DELETE FROM IDENTIFIERS CASCADE;
  DELETE FROM ORGANIZATIONS CASCADE WHERE ID BETWEEN 10000 AND 10005;
  DELETE FROM ADDRESSES CASCADE WHERE ID BETWEEN 10000 AND 10005;