package edu.duke.cabig.c3pr.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface C3PRStudyConsumerI {

  /**
   * Save or update Study
   *
   * @param study
   * @throws InvalidStudyException
   *	
   * @throws StudyCreateOrUpdateException
   *	
   */
  public void createOrUpdate(edu.duke.cabig.c3pr.domain.Study study) throws RemoteException, edu.duke.cabig.c3pr.grid.stubs.types.InvalidStudyException, edu.duke.cabig.c3pr.grid.stubs.types.StudyCreateOrUpdateException ;

}

