package edu.duke.cabig.c3pr.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public interface C3PRStudyConsumerI {

    public edu.duke.cabig.c3pr.domain.Study createOrUpdate(edu.duke.cabig.c3pr.domain.Study study) throws RemoteException, edu.duke.cabig.c3pr.grid.stubs.types.StudyValidationException, edu.duke.cabig.c3pr.grid.stubs.types.StudyCreateOrUpdateException ;

}

