
package edu.duke.cabig.c3pr.webservice.subjectregistry;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "NoSuchPatientExceptionFault", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService")
public class NoSuchPatientExceptionFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchPatientExceptionFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchPatientExceptionFaultMessage(String message, NoSuchPatientExceptionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public NoSuchPatientExceptionFaultMessage(String message, NoSuchPatientExceptionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: edu.duke.cabig.c3pr.webservice.subjectregistry.NoSuchPatientExceptionFault
     */
    public NoSuchPatientExceptionFault getFaultInfo() {
        return faultInfo;
    }

}
