
package edu.duke.cabig.c3pr.webservice.subjectregistry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubjectRegistryService", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", wsdlLocation = "file:/Users/kruttikagarwal/Documents/workspace/c3pr/documentation/design/essn/SubjectRegistry/SubjectRegistry.wsdl")
public class SubjectRegistryService
    extends Service
{

    private final static URL SUBJECTREGISTRYSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kruttikagarwal/Documents/workspace/c3pr/documentation/design/essn/SubjectRegistry/SubjectRegistry.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SUBJECTREGISTRYSERVICE_WSDL_LOCATION = url;
    }

    public SubjectRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubjectRegistryService() {
        super(SUBJECTREGISTRYSERVICE_WSDL_LOCATION, new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistryService", "SubjectRegistryService"));
    }

    /**
     * 
     * @return
     *     returns SubjectRegistry
     */
    @WebEndpoint(name = "SubjectRegistry")
    public SubjectRegistry getSubjectRegistry() {
        return (SubjectRegistry)super.getPort(new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistryService", "SubjectRegistry"), SubjectRegistry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubjectRegistry
     */
    @WebEndpoint(name = "SubjectRegistry")
    public SubjectRegistry getSubjectRegistry(WebServiceFeature... features) {
        return (SubjectRegistry)super.getPort(new QName("http://enterpriseservices.nci.nih.gov/SubjectRegistryService", "SubjectRegistry"), SubjectRegistry.class, features);
    }

}
