
package edu.duke.cabig.c3pr.webservice.subjectregistry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SubjectRegistry", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    edu.duke.cabig.c3pr.webservice.subjectregistry.ObjectFactory.class,
    edu.duke.cabig.c3pr.webservice.iso21090.ObjectFactory.class
})
public interface SubjectRegistry {


    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.InitiateSubjectRegistryResponse
     * @throws DuplicateStudySubjectExceptionFaultMessage
     * @throws InvalidSiteExceptionFaultMessage
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InvalidStudyProtocolExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "InitiateSubjectRegistryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public InitiateSubjectRegistryResponse initiateSubjectRegistry(
        @WebParam(name = "InitiateSubjectRegistryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        InitiateSubjectRegistryRequest parameters)
        throws DuplicateStudySubjectExceptionFaultMessage, InsufficientPrivilegesExceptionFaultMessage, InvalidSiteExceptionFaultMessage, InvalidStudyProtocolExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.UpdateSubjectRegistryStatusResponse
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "UpdateSubjectRegistryStatusResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public UpdateSubjectRegistryStatusResponse updateSubjectRegistryStatus(
        @WebParam(name = "UpdateSubjectRegistryStatusRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        UpdateSubjectRegistryStatusRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.UpdateSubjectRegistryStatusHistoryResponse
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "UpdateSubjectRegistryStatusHistoryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public UpdateSubjectRegistryStatusHistoryResponse updateSubjectRegistryStatusHistory(
        @WebParam(name = "UpdateSubjectRegistryStatusHistoryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        UpdateSubjectRegistryStatusHistoryRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.UpdateSubjectRegistryResponse
     * @throws NoSuchStudySubjectExceptionFaultMessage
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "UpdateSubjectRegistryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public UpdateSubjectRegistryResponse updateSubjectRegistry(
        @WebParam(name = "UpdateSubjectRegistryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        UpdateSubjectRegistryRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage, NoSuchStudySubjectExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @throws InvalidStudySubjectDataExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    public void importSubjectRegistry(
        @WebParam(name = "ImportSubjectRegistryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", mode = WebParam.Mode.INOUT, partName = "parameters")
        Holder<ImportSubjectRegistryRequest> parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidStudySubjectDataExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.QuerySubjectRegistryResponse
     * @throws InvalidQueryExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "QuerySubjectRegistryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public QuerySubjectRegistryResponse querySubjectRegistry(
        @WebParam(name = "QuerySubjectRegistryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        QuerySubjectRegistryRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, InvalidQueryExceptionFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns edu.duke.cabig.c3pr.webservice.subjectregistry.RetrieveSubjectDemographyHistoryResponse
     * @throws NoSuchPatientExceptionFaultMessage
     * @throws InsufficientPrivilegesExceptionFaultMessage
     */
    @WebMethod
    @WebResult(name = "RetrieveSubjectDemographyHistoryResponse", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
    public RetrieveSubjectDemographyHistoryResponse retrieveSubjectDemographyHistory(
        @WebParam(name = "RetrieveSubjectDemographyHistoryRequest", targetNamespace = "http://enterpriseservices.nci.nih.gov/SubjectRegistryService", partName = "parameters")
        RetrieveSubjectDemographyHistoryRequest parameters)
        throws InsufficientPrivilegesExceptionFaultMessage, NoSuchPatientExceptionFaultMessage
    ;

}
