package edu.duke.cabig.c3pr.grid.service.globus;

import edu.duke.cabig.c3pr.grid.service.StudyServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the StudyServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class StudyServiceProviderImpl{
	
	StudyServiceImpl impl;
	
	public StudyServiceProviderImpl() throws RemoteException {
		impl = new StudyServiceImpl();
	}
	

    public edu.duke.cabig.c3pr.grid.stubs.CreateStudyResponse createStudy(edu.duke.cabig.c3pr.grid.stubs.CreateStudyRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.CreateStudyResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.CreateStudyResponse();
    impl.createStudy(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.OpenStudyResponse openStudy(edu.duke.cabig.c3pr.grid.stubs.OpenStudyRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.OpenStudyResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.OpenStudyResponse();
    impl.openStudy(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.ApproveStudySiteForActivationResponse approveStudySiteForActivation(edu.duke.cabig.c3pr.grid.stubs.ApproveStudySiteForActivationRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.ApproveStudySiteForActivationResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.ApproveStudySiteForActivationResponse();
    impl.approveStudySiteForActivation(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.ActivateStudySiteResponse activateStudySite(edu.duke.cabig.c3pr.grid.stubs.ActivateStudySiteRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.ActivateStudySiteResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.ActivateStudySiteResponse();
    impl.activateStudySite(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.AmendStudyResponse amendStudy(edu.duke.cabig.c3pr.grid.stubs.AmendStudyRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.AmendStudyResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.AmendStudyResponse();
    impl.amendStudy(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.UpdateStudySiteProtocolVersionResponse updateStudySiteProtocolVersion(edu.duke.cabig.c3pr.grid.stubs.UpdateStudySiteProtocolVersionRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.UpdateStudySiteProtocolVersionResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.UpdateStudySiteProtocolVersionResponse();
    impl.updateStudySiteProtocolVersion(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.CloseStudyResponse closeStudy(edu.duke.cabig.c3pr.grid.stubs.CloseStudyRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.CloseStudyResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.CloseStudyResponse();
    impl.closeStudy(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.UpdateStudyStatusResponse updateStudyStatus(edu.duke.cabig.c3pr.grid.stubs.UpdateStudyStatusRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.UpdateStudyStatusResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.UpdateStudyStatusResponse();
    impl.updateStudyStatus(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.CloseStudySiteResponse closeStudySite(edu.duke.cabig.c3pr.grid.stubs.CloseStudySiteRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.CloseStudySiteResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.CloseStudySiteResponse();
    impl.closeStudySite(params.getMessage().getMessage());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.stubs.CloseStudySitesResponse closeStudySites(edu.duke.cabig.c3pr.grid.stubs.CloseStudySitesRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.stubs.CloseStudySitesResponse boxedResult = new edu.duke.cabig.c3pr.grid.stubs.CloseStudySitesResponse();
    impl.closeStudySites(params.getMessage().getMessage());
    return boxedResult;
  }

}
