package edu.duke.cabig.c3pr.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface StudyServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  public void createStudy(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void openStudy(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void approveStudySiteForActivation(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void activateStudySite(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void amendStudy(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void updateStudySiteProtocolVersion(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void closeStudy(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void updateStudyStatus(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void closeStudySite(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

  public void closeStudySites(gov.nih.nci.cabig.ccts.domain.Message message) throws RemoteException ;

}

