drop table scheduled_arms;
drop table epochs cascade;
drop table study_participant_assignments cascade;
drop table if exists healthcare_sites cascade;
drop table if exists organizations cascade;
drop table study_investigators cascade;
drop table study_sites cascade;
drop table studies cascade;
drop table investigators cascade;
drop table addresses cascade;
drop table participants cascade;
drop table hc_site_investigators cascade;
drop table arms cascade;
drop table identifiers cascade;
drop table study_personnels cascade;
drop table research_staffs cascade;
drop table subject_eligibility_answers cascade;
drop table subject_stratification_answers cascade;
drop table study_diseases cascade;
drop table disease_terms cascade;
drop table disease_categories cascade;
drop table stratification_criterion cascade;
drop table stratification_cri_per_ans cascade;
drop table if exists disease_history cascade;
drop table if exists anatomic_sites cascade;
drop table eligibility_criterias cascade;
drop table contact_mechanisms cascade;