DROP TABLE IF EXISTS CSM_APPLICATION CASCADE;

DROP TABLE IF EXISTS CSM_GROUP CASCADE;

DROP TABLE IF EXISTS CSM_PRIVILEGE	CASCADE;

DROP TABLE IF EXISTS CSM_PROTECTION_ELEMENT	CASCADE;

DROP TABLE IF EXISTS CSM_PROTECTION_GROUP	CASCADE;

DROP TABLE IF EXISTS CSM_PG_PE	CASCADE;

DROP TABLE IF EXISTS CSM_ROLE	CASCADE;

DROP TABLE IF EXISTS CSM_ROLE_PRIVILEGE	CASCADE;

DROP TABLE IF EXISTS CSM_USER	CASCADE;

DROP TABLE IF EXISTS CSM_USER_GROUP	CASCADE;

DROP TABLE IF EXISTS CSM_USER_GROUP_ROLE_PG	CASCADE;

DROP TABLE IF EXISTS CSM_USER_PE	CASCADE;