package gov.nih.nci.cabig.ctms.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class RegistrationConsumerImpl extends RegistrationConsumerImplBase {

	
	public RegistrationConsumerImpl() throws RemoteException {
		super();
	}
	
	public void newMethod() throws RemoteException {
		//TODO: Implement this autogenerated method
		throw new RemoteException("Not yet implemented");
	}

}

