package gov.nih.nci.cabig.ctms.service;

import java.rmi.RemoteException;

import org.globus.wsrf.config.ContainerConfig;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import gov.nih.nci.cabig.ctms.common.RegistrationConsumer;


/**
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.0
 * 
 */
public class RegistrationConsumerImpl extends RegistrationConsumerImplBase {

	   private static final String SPRING_CLASSPATH_EXPRESSION = "springClasspathExpression";

    private static final String DEFAULT_SPRING_CLASSPATH_EXPRESSION = "classpath:applicationContext-grid.xml";

    private static final String REGISTRATION_CONSUMER_BEAN_NAME = "registrationConsumerBeanName";

    private static final String DEFAULT_REGISTRATION_CONSUMER_BEAN_NAME = "registrationConsumer";


    private RegistrationConsumer consumer;
        
    public RegistrationConsumerImpl() throws RemoteException {
		super();
           String exp = ContainerConfig.getConfig().getOption(SPRING_CLASSPATH_EXPRESSION,
                        DEFAULT_SPRING_CLASSPATH_EXPRESSION);
        String bean = ContainerConfig.getConfig().getOption(REGISTRATION_CONSUMER_BEAN_NAME,
                        DEFAULT_REGISTRATION_CONSUMER_BEAN_NAME);
        ApplicationContext ctx = new ClassPathXmlApplicationContext(exp);
        this.consumer = (RegistrationConsumer) ctx.getBean(bean);
    }
	

	public void register(gov.nih.nci.cabig.ctms.grid.RegistrationType registration) throws RemoteException, gov.nih.nci.cabig.ctms.stubs.types.InvalidRegistration, gov.nih.nci.cabig.ctms.stubs.types.RegistrationFailed {
		//TODO: Implement this autogenerated method
		this.consumer.register(registration);
	}

}

