    package gov.nih.nci.cabig.ctms.common;

    import java.rmi.RemoteException;

    /**
     * This class is autogenerated, DO NOT EDIT.
     *
     * This interface represents the API which is accessable on the grid service from the client.
     *
     * @created by Introduce Toolkit version 1.0
     *
     */
    public interface RegistrationConsumer {

        public void register(gov.nih.nci.cabig.ctms.grid.RegistrationType registration) throws RemoteException, gov.nih.nci.cabig.ctms.stubs.types.InvalidRegistration, gov.nih.nci.cabig.ctms.stubs.types.RegistrationFailed ;

        public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException ;

    }
    
