DELETE FROM SUBJECT_ELIGIBILITY_ANSWERS;
DELETE FROM ELIGIBILITY_CRITERIAS;
DELETE FROM STUDY_PERSONNELS;
DELETE FROM RESEARCH_STAFFS;
DELETE FROM SCHEDULED_ARMS;
DELETE FROM IDENTIFIERS;
DELETE FROM ARMS;
DELETE FROM EPOCHS;
DELETE FROM STUDY_PARTICIPANT_ASSIGNMENTS;
DELETE FROM STUDY_SITES;
DELETE FROM HC_SITE_INVESTIGATORS;
DELETE FROM STUDIES;
DELETE FROM HEALTHCARE_SITES;
DELETE FROM PARTICIPANTS;
DELETE FROM ADDRESSES;
DELETE FROM STUDY_INVESTIGATORS;
DELETE FROM INVESTIGATORS;




