DELETE FROM SCHEDULED_ARMS;
DELETE FROM IDENTIFIERS;
DELETE FROM ARMS;
DELETE FROM EPOCHS;
DELETE FROM STUDY_PARTICIPANT_ASSIGNMENTS;
DELETE FROM STUDY_SITES;
DELETE FROM STUDIES;
DELETE FROM HEALTHCARE_SITES;
DELETE FROM PARTICIPANTS;
DELETE FROM ADDRESSES;
DELETE FROM STUDY_INVESTIGATORS;
DELETE FROM INVESTIGATORS;

INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10001','1','8745 Dakota Street','Craigsville','North Dakota','USA','98972');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10002','1','1792 Old Peach St','Atlanta','GA','USA','30431');

INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10001', '1','DUKE GRID ID', 'Duke University Comprehensive Cancer Center', '10001');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10002', '1', 'NCI GRID ID','Warren Grant Magnuson Clinical Center', '10002');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10003', '1', 'NCI GRID ID','National Cancer Institute', '10002');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10004', '1','C3PR GRID ID', 'C3PR', '10002');

INSERT INTO STUDIES (ID, VERSION, GRID_ID, SHORT_TITLE_TEXT, LONG_TITLE_TEXT, DESCRIPTION_TEXT, TARGET_ACCRUAL_NUMBER, BLINDED_INDICATOR, RANDOMIZED_INDICATOR, MULTI_INSTITUTION_INDICATOR, SPONSOR_CODE, PHASE_CODE, PRECIS_TEXT, DISEASE_CODE, MONITOR_CODE, STATUS, TYPE)
VALUES (10001, 0, 'B13B207A-2289-4350-9883-25492FC0E8EA', 'LMB-2 IMMUNOTOXIN IN TREATING PATIENTS WITH CHRONIC LYMPHOCYTIC LEUKEMIA OR PROLYMPHOCYTIC LEUKEMIA', 
'A PHASE II CLINICAL TRIAL OF ANTI-TAC(FV)-PE38 (LMB-2) IMMUNOTOXIN FOR TREATMENT OF CD25 POSITIVE CHRONIC LYMPHOCYTIC LEUKEMIA',
'PATIENTS RECEIVE LMB-2 IMMUNOTOXIN IV OVER 30 MINUTES ON DAYS 1, 3, AND 5. TREATMENT REPEATS EVERY 28 DAYS FOR UP TO 6 COURSES IN THE ABSENCE OF DISEASE PROGRESSION, NEUTRALIZING ANTIBODIES (I.E., > 75% OF THE ACTIVITY OF 1µG/ML OF LMB-2 IMMUNOTOXIN), OR UNACCEPTABLE TOXICITY.PATIENTS WHO ACHIEVE A COMPLETE RESPONSE RECEIVE UP TO 2 ADDITIONAL COURSES OF LMB-2 IMMUNOTOXIN. PATIENTS WHO RELAPSE AFTER ACHIEVING A COMPLETE OR PARTIAL RESPONSE FOR MORE THAN 2 MONTHS ARE ELIGIBLE FOR RETREATMENT AS DESCRIBED ABOVE.', 
200,
0,
1,
0, 
'NATIONAL CANCER INSTITUTE', 
'PHASE II TRAIL', 
'A PHASE II CLINICAL TRIAL',
'CANCER', 
'CANCER THERAPY EVALUATION PROGRAM',
'ACTIVE - TRIAL IS OPEN TO ACCRUAL',
'GENETIC THERAPEUTIC');

INSERT INTO EPOCHS (ID, VERSION, GRID_ID,NAME, STU_ID)
VALUES (10001,0,'EPOCHS GRID ID','TREATMENT EPOCH',10001);

INSERT INTO ARMS (ID, VERSION, GRID_ID, NAME, EPH_ID)
VALUES (10001, 0,'ARM GRID ID','ARM A',10001);
INSERT INTO ARMS (ID, VERSION, GRID_ID, NAME, EPH_ID)
VALUES (10002, 0,'ARM GRID ID2','ARM A',10001);
INSERT INTO ARMS (ID, VERSION, GRID_ID, NAME, EPH_ID)
VALUES (10003, 0,'ARM GRID ID3','ARM A',10001);

INSERT INTO IDENTIFIERS(ID, VALUE, TYPE, SOURCE, VERSION, PRIMARY_INDICATOR, STU_ID)
VALUES (10001, '04_C_0121', 'C3D IDENTIFIER', 'NATIONAL CANCER INSTITUTE', 0, 0, 10001);
INSERT INTO IDENTIFIERS(ID, VALUE, TYPE, SOURCE, VERSION, PRIMARY_INDICATOR, STU_ID)
VALUES (10002, 'NCT00080821', 'CLINICALTRAILS.GOV IDENTIFIER', 'NATIONAL CANCER INSTITUTE', 0, 0, 10001);
INSERT INTO IDENTIFIERS(ID, VALUE, TYPE, SOURCE, VERSION, PRIMARY_INDICATOR, STU_ID)
VALUES (10003, 'NCI-04-C-0121', 'PROTOCOL AUTHORITY IDENTIFIER', 'NATIONAL CANCER INSTITUTE', 0, 1, 10001);

INSERT INTO STUDY_SITES(ID, HCS_ID, STUDY_ID, VERSION, GRID_ID, ROLE_CODE, STATUS_CODE, IRB_APPROVAL_DATE, START_DATE, END_DATE)
VALUES (10001, 10004, 10001, 0, 'STUDY SITES GRID ID','SITE', 'ACTIVE', '09-JAN-2006', '09-FEB-2006', '09-FEB-2006'); 
