INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10001','1','8745 Dakota Street','Craigsville','North Dakota','USA','98972');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('10002','1','1792 Old Peach St','Atlanta','GA','USA','30431');

INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10001', '1','DUKE GRID ID', 'Duke University Comprehensive Cancer Center', '10001');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10002', '1', 'NCI GRID ID','Warren Grant Magnuson Clinical Center', '10002');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10003', '1', 'NCI GRID ID','National Cancer Institute', '10002');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,GRID_ID,NAME,ADDRESS_ID)
VALUES ('10004', '1','C3PR GRID ID', 'C3PR', '10002');