  DELETE FROM CONTACT_MECHANISMS;
  DELETE FROM RESEARCH_STAFF;
  DELETE FROM HC_SITE_INVESTIGATORS;
  DELETE FROM INVESTIGATORS;
  DELETE FROM IDENTIFIERS;
  DELETE FROM ORGANIZATIONS WHERE ID BETWEEN 10000 AND 10006 CASCADE;
  DELETE FROM ADDRESSES;