INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('1','1','8745 Dakota Street','Craigsville','North Dakota','USA','98972');
INSERT INTO ADDRESSES (ID,VERSION,STREET_ADDRESS,CITY,STATE_CODE,COUNTRY_CODE,POSTAL_CODE)
VALUES ('2','1','1792 Old Peach St','Atlanta','GA','USA','30431');

INSERT INTO HEALTHCARE_SITES (ID,VERSION,NAME,ADDRESS_ID)
VALUES ('1', '1', 'Duke University Comprehensive Cancer Center', '1');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,NAME,ADDRESS_ID)
VALUES ('2', '1', 'Warren Grant Magnuson Clinical Center', '2');
INSERT INTO HEALTHCARE_SITES (ID,VERSION,NAME,ADDRESS_ID)
VALUES ('3', '1', 'National Cancer Institute', '2');

SELECT ADDRESSES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT ADDRESSES_ID_SEQ.NEXTVAL FROM DUAL;

SELECT HEALTHCARE_SITES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT HEALTHCARE_SITES_ID_SEQ.NEXTVAL FROM DUAL;
SELECT HEALTHCARE_SITES_ID_SEQ.NEXTVAL FROM DUAL;