
package edu.duke.cabig.c3pr.webservice.studyutility;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StudyUtilityService", targetNamespace = "http://enterpriseservices.nci.nih.gov/StudyUtilityService", wsdlLocation = "file:/C:/temp/studyutility/StudyUtility.wsdl")
public class StudyUtilityService
    extends Service
{

    private final static URL STUDYUTILITYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.duke.cabig.c3pr.webservice.studyutility.StudyUtilityService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.duke.cabig.c3pr.webservice.studyutility.StudyUtilityService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/temp/studyutility/StudyUtility.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/temp/studyutility/StudyUtility.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STUDYUTILITYSERVICE_WSDL_LOCATION = url;
    }

    public StudyUtilityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudyUtilityService() {
        super(STUDYUTILITYSERVICE_WSDL_LOCATION, new QName("http://enterpriseservices.nci.nih.gov/StudyUtilityService", "StudyUtilityService"));
    }

    /**
     * 
     * @return
     *     returns StudyUtility
     */
    @WebEndpoint(name = "StudyUtility")
    public StudyUtility getStudyUtility() {
        return super.getPort(new QName("http://enterpriseservices.nci.nih.gov/StudyUtilityService", "StudyUtility"), StudyUtility.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudyUtility
     */
    @WebEndpoint(name = "StudyUtility")
    public StudyUtility getStudyUtility(WebServiceFeature... features) {
        return super.getPort(new QName("http://enterpriseservices.nci.nih.gov/StudyUtilityService", "StudyUtility"), StudyUtility.class, features);
    }

}
