package edu.duke.cabig.c3pr.grid.accrualservice.service.globus;

import edu.duke.cabig.c3pr.grid.accrualservice.service.AccrualServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the AccrualServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class AccrualServiceProviderImpl{
	
	AccrualServiceImpl impl;
	
	public AccrualServiceProviderImpl() throws RemoteException {
		impl = new AccrualServiceImpl();
	}
	

    public edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteAccrualReportResponse getSiteAccrualReport(edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteAccrualReportRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteAccrualReportResponse boxedResult = new edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteAccrualReportResponse();
    boxedResult.setSiteAccrualReport(impl.getSiteAccrualReport(params.getDiseaseSiteName(),params.getStudyShortTitleText(),params.getStartDate().getStartDate(),params.getEndDate().getEndDate()));
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetDiseaseSiteAccrualReportsResponse getDiseaseSiteAccrualReports(edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetDiseaseSiteAccrualReportsRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetDiseaseSiteAccrualReportsResponse boxedResult = new edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetDiseaseSiteAccrualReportsResponse();
    boxedResult.setDiseaseSiteAccrualReport(impl.getDiseaseSiteAccrualReports());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteCtepIdResponse getSiteCtepId(edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteCtepIdRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteCtepIdResponse boxedResult = new edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetSiteCtepIdResponse();
    boxedResult.setResponse(impl.getSiteCtepId());
    return boxedResult;
  }

    public edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetStudyAccrualReportsResponse getStudyAccrualReports(edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetStudyAccrualReportsRequest params) throws RemoteException {
    edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetStudyAccrualReportsResponse boxedResult = new edu.duke.cabig.c3pr.grid.accrualservice.stubs.GetStudyAccrualReportsResponse();
    boxedResult.setStudyAccrualReport(impl.getStudyAccrualReports());
    return boxedResult;
  }

}
